apiVersion: v1
kind: Namespace
metadata:
  name: business-frontend
  labels:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: business-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: inflate
        image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
        resources:
          requests:
            cpu: 0.5
      tolerations:
      - key: "workload"
        value: "test"
        operator: "Equal"
        effect: "NoSchedule"